name: Android Build CI

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        
      - name: Change gradle permissions
        run: | 
          chmod +x ./gradlew
  
      - name: Build the application using Gradle
        run: |
          ./gradlew clean
          ./gradlew build
      
      - name: Upload compiled apk to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: compiled-app
          path: app/build/outputs/apk/debug/app-debug.apk
